name: flowers_store
description: "A new Flutter project."
publish_to: 'none'

# Format: MAJOR.MINOR.PATCH+BUILD
# MAJOR: Incompatible changes (e.g., 1.0.0 to 2.0.0)
# MINOR: New features, no breaking changes (e.g., 1.0.0 to 1.1.0)
# PATCH: Bug fixes, no breaking changes (e.g., 1.0.0 to 1.0.1)
# BUILD: Incremented for each build or release (e.g., 1.0.0+001 to 1.0.0+002)
version: 0.1.1+8

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_custom_dropdown: ^3.0.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  chips_choice: ^3.0.1
  dartz: ^0.10.1
  easy_stepper: ^0.8.3
  equatable: ^2.0.5
  file_picker: any
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_localization: ^0.2.0
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  go_router: ^14.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  intl: any
  intl_phone_field: ^3.2.0
  json_annotation: ^4.9.0
  like_button: ^2.0.5
  multi_select_flutter: ^4.1.3
  path: ^1.9.0
  phone_form_field: ^9.2.4
  photo_view: ^0.14.0
  pinput: any
  readmore: ^3.0.0
  roundcheckbox: ^2.0.5
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  solar_icons: ^0.0.5
  syncfusion_flutter_sliders: ^25.1.42
  u_credit_card: ^1.2.2
  video_player: ^2.8.6
  widget_zoom: ^0.0.4
  shimmer: ^3.0.0
  
dev_dependencies:
  build_runner: ^2.4.9
 
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/lotties/
    - assets/illustration/
    - assets/images/
    - assets/shapes/
    - assets/icons/flags/
    - assets/icons/payment/
    - lib/herlpers/localization/locales/
    - assets/images/onboarding/
    - assets/images/splash/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/splash.png

  android_12:
    color: "#ffffff"
    image: assets/images/splash/splash_12.png
